name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev cmake build-essential
        
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install qt cmake
        
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install qt cmake
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..
        
    - name: Build project
      run: |
        cd build
        make -j4
        
    - name: Run tests
      run: |
        cd build
        ./test_paint  # ваш тестовий виконуваний файл
        
    - name: Generate coverage report
      run: |
        cd build
        make coverage
      # Додаємо звіт coverage до GitHub
