name: Coverage report

on: workflow_dispatch

jobs:
  coverage:
    run_on: macos-latest
    steps:
      - name: Get repository code 
        uses: actions/checkout@v3

      - name: Install dependencies 
        run: |
          brew install cmake qt googletest

      - name: Cofigure Cmake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build project
        run: |
          cd build
          cmake --build .

      - name: Make coverage report
        run:
          make coverage

      - name: Deploy coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/coverage_report

