name: Test Paint

permissions:
  contents: write

on: push

jobs:
  build:
    strategy:
     matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Get repository code 
        uses: actions/checkout@v3

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake qt tools-dev cmake build-essential

      - name: Install dependencies (windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install qt cmake ninja
        
      - name: Install dependencies (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-

      - name: Configure CMake (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cmake -S . -B build -DCMAKE_PREFIX_PATH=$(brew --prefix qt)

      - name: Canfigure Cmake (windows/linux)
        if: matrix.os != 'macos-latest'
        run: |
          cmake -S . -B build

      - name: Build project (macOS/Linux)
        if: matrix.os != 'windows-latest'
        run: |
          cmake --build build -- -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 2)

      - name: Build project (windows)
        if: matrix.os == 'windows-latest'
        run: |
          cmake --build build --config Release

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

  slang-format:
    runs-on: macos-latest
    steps:
      - name: Get repository code 
        uses: actions/checkout@v3

      - name: Install slang-format
        run: |
          brew update
          brew install clang-format

      - name: Run clang-format (fix)
        run: |
          clang-format -i $(find . -type f \( -name "*.cpp" -o -name "*.h" \))

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Apply clang-format fixes" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}