name: Test Paint

permissions:
  contents: write

on: push

jobs:
  build-macOS:
    runs-on: macos-latest
    steps:
      - name: Get repository code 
        uses: actions/checkout@v3

      - name: Install dependencies 
        run: |
          brew update
          brew install cmake qt googletest

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_PREFIX_PATH=$(brew --prefix qt)

      - name: Build project
        run: |
          cmake --build build -- -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 2)

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code 
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-tools-dev cmake ninja-build build-essential libgtest-dev
          # зібрати gtest з сирців
          cd /usr/src/googletest
          sudo cmake -B build
          sudo cmake --build build --target install

      - name: Configure CMake
        run: |
          cmake -S . -B build
      
      - name: Build project
        run: |
          cmake --build build -- -j$(nproc 2>/dev/null || sysctl -n hw.ncpu 2>/dev/null || echo 2)

      - name: Run tests
        run: |
          export QT_QPA_PLATFORM=offscreen
          ctest --output-on-failure --test-dir build

  slang-format:
    runs-on: macos-latest
    steps:
      - name: Get repository code 
        uses: actions/checkout@v3

      - name: Install slang-format
        run: |
          brew update
          brew install clang-format

      - name: Run clang-format (fix)
        run: |
          clang-format -i $(find . -type f \( -name "*.cpp" -o -name "*.h" \))

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Apply clang-format fixes" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}